# Generated by Django 4.2.9 on 2024-02-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entity_entitytype_field_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_image_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='is_title_field',
            field=models.BooleanField(default=False),
        ),
    ]
