# Generated by Django 4.2.9 on 2024-02-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_field_is_image_field_field_is_title_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='image_field_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='title_field_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
