# Generated by Django 4.2.9 on 2024-02-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entitytype_image_field_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
