# Generated by Django 4.2.9 on 2024-02-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_entity_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='field_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='relationshiptype',
            old_name='label',
            new_name='name',
        ),
    ]
