# Generated by Django 4.2.9 on 2024-02-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_entity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
