# Generated by Django 4.2.9 on 2024-02-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='color',
            field=models.CharField(default='black', max_length=255),
            preserve_default=False,
        ),
    ]
