# Generated by Django 4.2.9 on 2024-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entity_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='color',
        ),
        migrations.AddField(
            model_name='entitytype',
            name='color',
            field=models.CharField(default='black', max_length=255),
            preserve_default=False,
        ),
    ]
