# Generated by Django 4.2.9 on 2024-02-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_entity_color_entitytype_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graph',
            new_name='Network',
        ),
    ]
