# Generated by Django 4.2.9 on 2024-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entity_end_date_entity_image_url_entity_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytype',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='title_field_name',
            field=models.CharField(max_length=255),
        ),
    ]
