# Generated by Django 5.0.2 on 2024-04-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_entity_end_date_alter_entity_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEdits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
