# Generated by Django 5.0.2 on 2024-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_useredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredits',
            name='subtitle',
            field=models.CharField(default='Exploring the connections of artistic production', max_length=255),
        ),
    ]
