# Generated by Django 5.0.2 on 2024-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='blurb',
            field=models.TextField(default='Welcome'),
        ),
    ]
