# Generated by Django 5.0.2 on 2024-04-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_about_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='blurb',
            field=models.CharField(max_length=255),
        ),
    ]
