# Generated by Django 5.0.2 on 2024-04-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_about_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredits',
            name='logoURL',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
