# Generated by Django 4.2.9 on 2024-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_about_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='blurb',
            field=models.TextField(default='  '),
        ),
        migrations.AlterField(
            model_name='entity',
            name='end_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entity',
            name='start_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='color',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='end_date_field_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='image_field_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='start_date_field_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='title_field_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useredits',
            name='contributors',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='useredits',
            name='logoURL',
            field=models.TextField(default='  '),
        ),
        migrations.AlterField(
            model_name='useredits',
            name='subtitle',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='useredits',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
