# Generated by Django 4.2.9 on 2024-05-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='blurb',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useredits',
            name='contributors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='useredits',
            name='logoURL',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='useredits',
            name='subtitle',
            field=models.TextField(null=True),
        ),
    ]
