# Generated by Django 4.2.9 on 2025-06-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_googlesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of image urls for carousel'),
        ),
    ]
